{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-alpaca
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/alpaca_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/alpaca/alpaca_{{ version }}.tar.gz
  sha256: f3723317db5e307ae0043ac2954926b620f6ecfcb2ba34cc84704b9571fe2c2b

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('c') }}          # [not win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - libgomp                      # [linux]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-data.table
    - r-formula
    - r-mass
    - r-rcpp
    - r-rcpparmadillo
    - libblas
    - liblapack
  run:
    - r-base
    - r-data.table
    - r-formula
    - r-mass
    - r-rcpp
    - r-rcpparmadillo

test:
  commands:
    - $R -e "library('alpaca')"           # [not win]
    - "\"%R%\" -e \"library('alpaca')\""  # [win]

about:
  home: https://github.com/amrei-stammann/alpaca
  license: GPL-3.0-only
  summary: Provides a routine to partial out factors with many levels during the optimization of the log-likelihood function of the corresponding generalized linear model (glm). The package is based on the algorithm described in Stammann (2018) <arXiv:1707.01815> and is restricted to glm's that are based on maximum likelihood
    estimation and nonlinear. It also offers an efficient algorithm to recover estimates of the fixed effects in a post-estimation routine and includes robust and multi-way clustered standard errors. Further the package provides analytical bias corrections for binary choice models derived by Fernandez-Val and Weidner (2016)
    <doi:10.1016/j.jeconom.2015.12.014> and Hinz, Stammann, and Wanner (2020) <arXiv:2004.12655>.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - skreu
